/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WorldTime;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        WorldTime tmp = new WorldTime();
        System.out.println(tmp.getTimeByCountry("Japan"));
    }
}
